// Shared numeric thresholds used by analysis + visualization.

export const METRIC_STRENGTH_CUTOFFS = {
  STRONG: 0.75,
  MEDIUM: 0.5,
};

export const SCORE_BAND_BOUNDARIES = {
  NEGATIVE: 0,
  DISSONANT_MARGINAL_MIN: -0.5,
  DISSONANT_GOOD_MIN: 1.0,
};

export const PENALTY_MULTIPLIERS = {
  HALF: 0.5,
  QUARTER: 0.25,
  THREE_QUARTER: 0.75,
};

export const TWO_VOICE_SCORING = {
  MIN_INTERVAL_DURATION: 0.25,
  IMPERFECT_CONSONANCE_BASE: 0.5,
  PERFECT_FIFTH_BASE: 0.3,
  PERFECT_FOURTH_BASE: 0.25,
  OTHER_CONSONANCE_BASE: 0.2,
  GOOD_RESOLUTION_BONUS: 0.3,
  BAD_RESOLUTION_PENALTY: 0.2,
  REPETITION_PENALTY_BASE: 0.15,
  PARALLEL_BASE_PENALTY: 1.0,
  MOTION_STEPWISE_BONUS: 0.1,
};
